#!/usr/bin/env node
/**
 * Write the evidence layer as a directory of files, with no server behind it.
 *
 *   node packages/delivery/src/export.ts [outDir]
 *
 * The API in api.ts reads a 13 GB data root: archives, snapshots, a six-million
 * row SQLite index. None of that can go on a small host, and most of it does not
 * need to. What a reader has to be able to check is small:
 *
 *   which copies exist, and what each one hashes to
 *   what changed between two of them, field by field
 *   what cannot be recovered
 *   the code that recomputes the digest and reads the chain
 *
 * That is a few megabytes. So this writes those answers as flat files at exactly
 * the paths the API serves them from, and the same pages render against either.
 * A static site cannot answer one reader differently from another, cannot fall
 * over under load, and can be mirrored by anyone who distrusts us — which for
 * this project is a feature and not a compromise.
 *
 * What is deliberately NOT exported: the analytics, OCDS and tender endpoints.
 * They need the index, they are a different product from the evidence layer, and
 * shipping a stale copy of them would be worse than not shipping them.
 */

import { cp, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATALOGUE, DEFAULT_LANG, type Lang, LANGS, t } from './i18n.ts';
import { anchorAddress, anchorNode, chainSnapshot } from './chain.ts';
import {
  bundleChanges,
  bundleFields,
  bundleSummaries,
  captures,
  count,
  feed,
  index,
  monthVersions,
  recovery,
  storedMonths,
} from './data.ts';
import { loadBundle } from '../../cli/src/bundles.ts';
import { listBundles } from '../../cli/src/bundles.ts';

const HERE = fileURLToPath(new URL('.', import.meta.url));

/**
 * The image is Caddy plus these files. Written into the export rather than kept
 * in the repo root so the deployable directory is self-contained: everything
 * uploaded is something a reader could have downloaded.
 */
const DEPLOY_DOCKERFILE = `# Generated by packages/delivery/src/export.ts. Edit the Caddyfile in the repo.
# renovate: image=caddy tag=2.11.4-alpine
FROM caddy:2.11.4-alpine

COPY Caddyfile /etc/caddy/Caddyfile
COPY site /srv

# Fails the build on a malformed Caddyfile rather than at container start, where
# Railway would report it as a crash loop with no useful message.
RUN caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile

EXPOSE 8080
`;
const WEB = resolve(HERE, '../../../apps/web');
const VERIFIER = resolve(HERE, '../../../apps/verifier');

/**
 * Write a JSON response as `<path>/index`.
 *
 * Not as `<path>` itself, because `/api/bundles` is both a response and the
 * parent of `/api/bundles/202608/...`, and a path cannot be a file and a
 * directory at once. The Caddyfile does `try_files {path} {path}/index`, so the
 * URL a reader uses is the same one the live API serves.
 */
async function json(path: string, body: unknown): Promise<number> {
  await mkdir(path, { recursive: true });
  const text = JSON.stringify(body, null, 2);
  await writeFile(join(path, 'index'), text, 'utf8');
  return Buffer.byteLength(text);
}

async function jsonFile(path: string, body: unknown): Promise<number> {
  await mkdir(join(path, '..'), { recursive: true });
  const text = JSON.stringify(body, null, 2);
  await writeFile(path, text, 'utf8');
  return Buffer.byteLength(text);
}

const mb = (n: number) => `${(n / 1_048_576).toFixed(2)} MB`;

export async function exportSite(outDir: string, log: (s: string) => void = () => {}) {
  // Everything served lives under site/, and the deploy files sit beside it.
  // Not flat: the Dockerfile would then have to exclude itself from its own
  // build context, and Railway's builder honours .dockerignore when it packs
  // the context, so the Dockerfile it was told to use disappears before it runs.
  const site = join(outDir, 'site');
  const api = join(site, 'api');
  let bytes = 0;

  // The pages, verbatim. No build step, so what is served is what is in the repo.
  await mkdir(site, { recursive: true });
  await cp(WEB, site, { recursive: true });
  // Tests are for the repo, not for a reader's browser.
  await cp(VERIFIER, join(site, 'verifier'), {
    recursive: true,
    filter: (src) => !src.includes(`${sep}test`),
  });
  log('pages copied');

  // Extensionless files at the API's own paths, so the page needs no static mode.
  const chain = await chainSnapshot();
  // The root listing is the one response with no children, so it is a plain file
  // and `/api` resolves straight to it.
  bytes += await jsonFile(join(api, 'index'), {
    name: t('app.name', DEFAULT_LANG),
    tagline: t('app.tagline', DEFAULT_LANG),
    anchor: { address: anchorAddress(), node: anchorNode() },
    endpoints: ['/api/versions', '/api/bundles', '/api/recovery'],
    languages: LANGS,
    defaultLanguage: DEFAULT_LANG,
    /**
     * Stated so a reader knows what they are looking at. A static export is a
     * point-in-time copy, and a page that hides that is claiming to be live.
     */
    static: true,
    exportedAt: new Date().toISOString(),
  });

  for (const lang of LANGS) {
    bytes += await json(join(api, 'i18n', lang), {
      lang,
      messages: CATALOGUE[lang as Lang],
    });
  }

  const caps = await captures();
  bytes += await json(join(api, 'versions'), {
    anchor: { address: chain.address, node: chain.node, reachable: chain.reachable },
    anchorStateKnown: chain.reachable,
    captures: caps.map(({ path: _path, ...rest }) => rest),
  });
  log(`versions: ${caps.length} captures`);

  const inv = await recovery();
  bytes += await json(join(api, 'recovery'), {
    anchorStateKnown: chain.reachable,
    caveat: chain.reachable ? null : 'chain unreachable when this was exported',
    inventory: inv,
  });

  /**
   * The change feed, and the two counts the front page renders beside it.
   *
   * These used to be left out, so index.html asked a static host for /stats,
   * /changes and /months, got three 404s, and rendered an error where its table
   * belongs — which is why /evidencia/index.html was redirected away to
   * versions.html and the site's own "Changes" tab did nothing.
   *
   * Every change is written once, unpaged and unfiltered, because the feed is
   * the flattened watch reports and that is hundreds of rows at most. The page
   * filters and pages in the browser, the same way the version browser does, so
   * one payload serves a live API and a folder of files identically.
   *
   * Language-dependent labels are deliberately NOT baked in: the page already
   * fetches the message catalogue and can name a kind itself. Baking them would
   * mean one export per language for data that is identical in both.
   */
  const items = await feed();
  const byKind: Record<string, number> = {};
  for (const i of items) byKind[i.kind] = (byKind[i.kind] ?? 0) + 1;
  bytes += await json(join(api, 'changes'), {
    meta: {
      total: items.length,
      limit: items.length,
      offset: 0,
      byKind,
      indexAvailable: index() !== null,
      institutionFilterUsable: index() !== null,
      static: true,
    },
    changes: items.map((i) => ({
      detectedAt: i.detectedAt,
      month: i.month,
      closedMonth: i.closedMonth,
      previousStamp: i.previousStamp,
      currentStamp: i.currentStamp,
      kind: i.kind,
      table: i.table,
      id: i.id,
      before: i.before ?? null,
      after: i.after ?? null,
      proof: `/proof/${i.month}/${encodeURIComponent(i.table)}/${encodeURIComponent(i.id)}`,
    })),
  });
  log(`changes: ${items.length}`);

  const monthList = [];
  for (const m of await storedMonths()) {
    const versions = await monthVersions(m);
    monthList.push({ month: m, versions: versions.length, stamps: versions.map((v) => v.stamp) });
  }
  bytes += await json(join(api, 'months'), { months: monthList, total: monthList.length });

  const hasIndex = index() !== null;
  bytes += await json(join(api, 'stats'), {
    index: {
      available: hasIndex,
      note: null,
      tenders: hasIndex ? count('tender') : 0,
      contracts: hasIndex ? count('contract') : 0,
      suppliers: hasIndex ? count('supplier') : 0,
      institutions: hasIndex ? count('institution') : 0,
      appeals: hasIndex ? count('appeal') : 0,
    },
    archives: { months: monthList.length },
    changes: { total: items.length, byKind },
    anchors: {
      days: chain.days.length,
      latest: chain.latest,
      address: chain.address,
      reachable: chain.reachable,
    },
  });

  const summaries = await bundleSummaries();
  bytes += await json(join(api, 'bundles'), { bundles: summaries });
  log(`bundles: ${summaries.length}`);

  const stored = await listBundles();
  for (const b of summaries) {
    const base = join(api, 'bundles', b.period, b.pair);
    const hit = stored.find((x) => x.period === b.period && x.pair === b.pair);
    if (!hit) continue;

    const onChain =
      chain.diffs.find(
        (d) =>
          d.period === hit.manifest.period &&
          d.canonVersion === hit.manifest.canonVersion &&
          d.fromId === hit.manifest.from.archiveSha256.slice(0, 12) &&
          d.toId === hit.manifest.to.archiveSha256.slice(0, 12),
      ) ?? null;

    bytes += await json(base, {
      manifest: hit.manifest,
      onChain,
      digestMatches: onChain ? onChain.bundleDigest === hit.manifest.bundleDigest : null,
      anchorStateKnown: chain.reachable,
    });
    bytes += await json(join(base, 'fields'), {
      period: b.period,
      pair: b.pair,
      ...(await bundleFields(b.period, b.pair)),
    });
    const readable = await bundleChanges(b.period, b.pair, { readable: true });
    bytes += await json(join(base, 'changes'), { period: b.period, pair: b.pair, ...readable });

    // The whole artifact, unmodified, so a reader can verify the digest against
    // the file rather than against our summary of it.
    const raw = join(hit.dir, 'changes.jsonl.gz');
    await cp(raw, join(base, 'changes.jsonl.gz'));
    await writeFile(
      join(base, 'manifest.json'),
      `${JSON.stringify(hit.manifest, null, 2)}\n`,
      'utf8',
    );
    log(`  ${b.period} ${b.pair}: ${readable?.matched ?? 0} readable rows`);
  }

  // The export is the deployable. Railway's uploader honours .gitignore, and
  // dist/ is ignored there for good reason — 22 MB of derived data per
  // republication does not belong in git history. Rather than fight that, the
  // export carries its own Dockerfile and Caddyfile so `cd dist && railway up`
  // sends exactly the site and nothing else.
  await cp(resolve(HERE, '../../../Caddyfile'), join(outDir, 'Caddyfile'));
  await writeFile(join(outDir, 'Dockerfile'), DEPLOY_DOCKERFILE, 'utf8');
  // The deploy config travels with the deployable too. Without it Railway sees an
  // unconfigured service, falls back to auto-detection, and tries to build a
  // directory of JSON as a Node application.
  await mkdir(join(outDir, '.railway'), { recursive: true });
  await cp(resolve(HERE, '../../../.railway/railway.ts'), join(outDir, '.railway/railway.ts'));
  log('deploy files written');

  log(`\n${mb(bytes)} of JSON written to ${outDir}`);
  log(`deploy with: cd ${outDir} && railway up --service ancla`);
  return { outDir, bytes, bundles: summaries.length, captures: caps.length };
}

/**
 * Default output: beside the mirror, outside the repo.
 *
 * Not `./dist`. `railway up` walks up to the git root and applies .gitignore, and
 * dist/ is ignored there — so deploying from inside it uploaded 1.4 MB of
 * whatever happened not to match a rule, without the Dockerfile. The data root
 * is already outside the repo for the same class of reason.
 */
export function defaultOutDir(): string {
  const root = process.env.ANCLA_DATA ?? join(process.env.HOME ?? '.', 'ancla-data');
  return join(root, 'site');
}

const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const out = process.argv[2] ?? defaultOutDir();
  await exportSite(out, (s) => process.stdout.write(`${s}\n`));
}
